### ISSUE TITLE
why you share those stuff?

### ISSUE THREAD

**Issue by randomwangran** [rememberYou/dotfiles#1]
Indeed, I learn from you. Thank you.

Just curious about it. 

Those configurations are your power? (maybe I am wrong)

But, I am a big fan of Belgian cyclist: Greg Van Avermaet.

As a professional cyclist, he shares some info on Internet, i.e., Strava.

BUT, he never show his Power/Heartrate data (which is critical to cyclist lovers, such as me) to the public.

Things are different in the realm of computers. Lots of amazing guys share their crafts and I've learned a lot from these guys.

Just want to know your opinion.

**Comment by rememberYou** [comment]
First of all, I am delighted to see that these dotfiles have been able to help you to learn more.

If I understood your question correctly, you would like my feedback on sharing configuration files. Let's turn this question around, why shouldn't we share our configurations? What I mean is that as long as you have take care to not share your critical information (_e.g._ passwords, tokens, _etc._), there is no risk of having security issues.

For me, the world of open-source is above all a world of sharing. Its strength is its community. If no one would share any files, then we would stay on our toes and evolve a lot less. The benefit of sharing your files allows others persons to deepen their configuration with yours, contribute on your dotfiles and also to ask questions.

In addition, save your configuration files on Git makes it easier for you to backup your files since you will only make backups of sensitive data that is not shared. Thus, an installation of your OS is done quickly since on the basis of your Git repository, you will find all your previous configurations.

To return to the analogy of cyclists, it is of course quite normal that cyclists do not show all their data because there are those who are more sensitive than others and for whom critical information could be deduced.

To take another example such as Formula One racing, each manufacturer has its own manufacturing secrets and fortunately these data are not shared, otherwise we would only have similar cars that would have the same advantages and disadvantages.

**NOTE:** I don't recommend Strava at all, I think that there is too much information shared, at least enough to allow a malicious person to hurt you.

Always favoured open-source applications whenever possible. Your data is the most important thing you have, take care of it.

Without going into too much detail, I hope I was able to answer your question 😊
